# Generated by Django 5.0.7 on 2024-08-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
