# Generated by Django 5.0.7 on 2024-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='summary',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='summary_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
