# Generated by Django 5.0.7 on 2024-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listing_summary_listing_summary_up_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='summary_up_to_date',
            field=models.BooleanField(default=True),
        ),
    ]
