# Generated by Django 5.0.7 on 2024-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_reviewer_name_review_reviewer_review_reviewee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
