# Generated by Django 5.0.7 on 2024-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_listing_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='summary_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
